// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVqKIYyBO_DtPstnAcl_r1yzFObfns2pg',
    appId: '1:692101396287:web:1a9cc698d72ddc38ae458a',
    messagingSenderId: '692101396287',
    projectId: 'task-mangement-apps',
    authDomain: 'task-mangement-apps.firebaseapp.com',
    storageBucket: 'task-mangement-apps.appspot.com',
    measurementId: 'G-K09VJDNRJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQBV5oIBEZHhlbUzsrjENP2WuHXKUqVQ0',
    appId: '1:692101396287:android:32c0b13f5a274a5cae458a',
    messagingSenderId: '692101396287',
    projectId: 'task-mangement-apps',
    storageBucket: 'task-mangement-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf0RqtWW_24UwaDsxFFz_B05NSZLm3n_8',
    appId: '1:692101396287:ios:3d46f14829d17ee3ae458a',
    messagingSenderId: '692101396287',
    projectId: 'task-mangement-apps',
    storageBucket: 'task-mangement-apps.appspot.com',
    androidClientId: '692101396287-la4ugfgu5nhjgugutued2n5pkv5li8kn.apps.googleusercontent.com',
    iosClientId: '692101396287-o7ksn4ns58d5siisbgnj963creqd0uev.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf0RqtWW_24UwaDsxFFz_B05NSZLm3n_8',
    appId: '1:692101396287:ios:3d46f14829d17ee3ae458a',
    messagingSenderId: '692101396287',
    projectId: 'task-mangement-apps',
    storageBucket: 'task-mangement-apps.appspot.com',
    androidClientId: '692101396287-la4ugfgu5nhjgugutued2n5pkv5li8kn.apps.googleusercontent.com',
    iosClientId: '692101396287-o7ksn4ns58d5siisbgnj963creqd0uev.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
